name: Cloud PC Tailscale

on:
  workflow_dispatch:

jobs:
  cloudpc:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: Atualizar sistema
        run: sudo apt update

      - name: Instalar Tailscale
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh

      - name: Subir Tailscale
        run: |
          sudo tailscale up --authkey=${{ secrets.TS_AUTHKEY }} --hostname=github-cloud-pc

      - name: Mostrar IP
        run: tailscale ip -4

      - name: Manter ligado
        run: sleep 21600
